### ISSUE TITLE
Excel error if no styles are defined

### ISSUE THREAD

**Issue by sod** [dunkelrot/elxml#11]
If you don't define any styles, Excel (2010) throws an "error in styles.xml".

#### Sample code:
```node
var excel = require("elxml");

var wb = excel.createWorkbook();
// wb.createStyle("Standard");
var sheet = wb.addSheet('test sheet');
var row = sheet.addRow(1);
row.addCell('A').setValue('test value');
wb.save('test-file.xlsx', function() {});
```

if you include the line `wb.createStyle("Standard");`, the error goes away.

These are the lines that change in styles.xml:

#### styles.xml without styles (that throws the error):
```xml
<cellStyleXfs count="0"/>
<cellXfs count="0"/>
<cellStyles count="0"/>
```

#### styles.xml with styles:
```xml
<cellStyleXfs count="1">
	<xf numFmtId="0" fontId="0" fillId="0" borderId="0"/>
</cellStyleXfs>
<cellXfs count="1">
	<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
</cellXfs>
<cellStyles count="1">
	<cellStyle name="Standard" xfId="0" builtinId="0"/>
</cellStyles>
```

Maybe these tags must not be empty or self closing?

btw. awesome module. Thanks for sharing! :-)

**Comment by dunkelrot** [comment]
Thanks for reporting this issue!
I have change the init code: By default a 'Standard' style is created and can be accessed via wb.getStyle('Standard'). Old code will continue to work without any modifications.
