### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sqrammi** [dunkelrot/elxml#13]
Hi. This is a great library! Have you decided what the licensing for it is going to be? MIT, hopefully :) ?

**Comment by dunkelrot** [comment]
please take a look at the LICENSE document, I guess it is MIT, at least that was/is my intention

**Comment by sqrammi** [comment]
Ah, I guess it hasn't been added to the package.json file, so npm was complaining.

**Comment by dunkelrot** [comment]
The package.json has an entry but perhaps with the wrong format. Will check. The npm web page reports "MIT". I'm not sure what is wrong with the package.json...

**Comment by dunkelrot** [comment]
The package.json used a deprecated format for the license entry. I changed that to the current format. Should be fixed.

**Comment by dunkelrot** [comment]
Closed
