### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by mikecole** [dunkelrot/elxml#15]
I'm currently getting Can't resolve 'fs' errors in several modules:

Module not found: Error: Can't resolve 'fs' in '\node_modules\archiver\lib'
Module not found: Error: Can't resolve 'fs' in \node_modules\elxml'
Module not found: Error: Can't resolve 'fs' in '\node_modules\fs.realpath'
Module not found: Error: Can't resolve 'fs' in '\node_modules\glob'
Module not found: Error: Can't resolve 'fs' in '\node_modules\graceful-fs'

**Comment by dunkelrot** [comment]
I have no idea how this can happen. What has changed in your environment? New version of NodeJS or NPM? 
What happens if you write and execute a simple script that requires 'fs'?

**Comment by mikecole** [comment]
This was a new install so a change in my environment is not a factor. This might be a dumb question, but this should be able to run in the browser, right?

**Comment by dunkelrot** [comment]
It was not designed to run in the browser. The dependency to 'fs' can be removed from Elxml but I don't know how to avoid the other package dependencies.

**Comment by mikecole** [comment]
Since I'm somewhat new to the ecosystem, can you explain how I would know it wasn't designed for the browser? Are there things I should be looking for? Thanks!

**Comment by dunkelrot** [comment]
It mainly depends on dependencies to nodeJS modules which are linked to OS libraries, like 'fs' or 'process'. Unfortunately this is not visible from the package.json file. As far as I know the module author will make a note in a readme about the compatibility with the browser. I usually checked if the author made a reference to bower but bower is deprecated these days. Bower was for the browser what npm is for nodeJS.

There might be a better way but for me it is some kind of trial and error. At the end the number of direct and indirect dependencies is often high which makes it even more difficult.
 
There are other Excel JavaScript libs on npm which might fit better to your needs and don't depend on nodeJS libs.

**Comment by mikecole** [comment]
Fair enough. Just trying to make this a learning experience. Thanks for your help.
